Create confirmation dialog for exiting
Enable capturing errors from dialog to ease debug

diff --git a/files/usr/lib/jeos-firstboot b/files/usr/lib/jeos-firstboot
--- a/files/usr/lib/jeos-firstboot
+++ b/files/usr/lib/jeos-firstboot
@@ -86,12 +86,47 @@ let dh_menu=LINES-15
 let dh_text=LINES-5
 
 d(){
-    if dialog --backtitle "$PRETTY_NAME" "$@" 2>"$dialog_out"; then
-	# need || true as dialog doesn't write newlines
-	read result < $dialog_out || true
-    else
-	return $?
-    fi
+    retval=
+    cmd='dialog --backtitle "$PRETTY_NAME" "$@" 2>"$dialog_out"'
+    while true
+    do
+        eval $cmd
+        retval=$?
+        case $retval in
+          0)
+            # need || true as dialog doesn't write newlines
+            read result < $dialog_out || true
+            return $retval
+            ;;
+          1)
+            dialog --yesno $"Do you really want to quit?" 0 0
+            retval=$?
+            case $retval in
+                0)
+                    exit 0;;
+                1|255)
+                    continue;;
+            esac
+            ;;
+          255)
+            # xargs to remove whitespaces
+            result_error=`cat $dialog_out|xargs`
+            if [ -z "$result_error" ]; then
+                dialog --yesno $"Do you really want to quit?" 0 0
+                retval=$?
+                case $retval in
+                    0)
+                        exit 0;;
+                    1|255)
+                        continue;;
+                esac
+            fi
+            logger -p err -t jeos-firstboot "$result_error"
+            dialog --msgbox $"Exiting due to error, please check system log" 0 0
+            exit 2
+            ;;
+        esac
+    done
 }
 
 warn(){
