Move timezone and network config
add apply functions to locale/keytable

diff --git a/files/usr/lib/jeos-firstboot-functions b/files/usr/lib/jeos-firstboot-functions
--- a/files/usr/lib/jeos-firstboot-functions
+++ b/files/usr/lib/jeos-firstboot-functions
@@ -40,4 +40,18 @@ findlocales()
         [ -n "$list" ]
 }
 
+apply_locale()
+{
+	if [ ! -z "$JEOS_LOCALE" ]; then
+		run langset.sh $JEOS_LOCALE || warn $"Setting the locale failed"
+	fi
+}
+
+apply_locale_and_keytable()
+{
+	if [ ! -z "$JEOS_LOCALE" -a ! -z "$JEOS_KEYTABLE" ]; then
+		# Activate the selected keyboard layout
+		run langset.sh "$JEOS_LOCALE" "$JEOS_KEYTABLE" || warn $"Setting the keyboard layout failed"
+	fi
+}
 # vim: syntax=sh
