Remove locale and keytable variables

diff --git a/files/usr/lib/jeos-firstboot b/files/usr/lib/jeos-firstboot
--- a/files/usr/lib/jeos-firstboot
+++ b/files/usr/lib/jeos-firstboot
@@ -104,10 +104,13 @@ sleep 1
 
 systemd_firstboot_args=('--setup-machine-id')
 
+# If the configuration is not loaded and we are in the first terminal
+# instance, make sure that the variables are declared.
+JEOS_LOCALE=${JEOS_LOCALE-}
+JEOS_KEYTABLE=${JEOS_KEYTABLE-}
+
 result=
 list=
-keytable=''
-locale=''
 password=''
 
 let dh_menu=LINES-15
@@ -200,17 +203,11 @@ if [ -z "$JEOS_LOCALE" ]; then
         newlocale="${result}"
     fi
 
-    if [ -n "$newlocale" ]; then
-        locale="${newlocale}.UTF-8"
-        systemd_firstboot_args+=("--locale=$locale")
-
-        # Run langset to get consolefont and keymap set up
-        run langset.sh $locale || warn $"Setting the locale failed"
-    fi
-else
-    locale="$JEOS_LOCALE"
-    systemd_firstboot_args+=("--locale=$locale")
+    JEOS_LOCALE="${newlocale}.UTF-8"
 fi
+
+run langset.sh $JEOS_LOCALE || warn $"Setting the locale failed"
+systemd_firstboot_args+=("--locale=$JEOS_LOCALE")
 
 if [ -z "$JEOS_KEYTABLE" ]; then
     default="us"
@@ -220,24 +217,22 @@ if [ -z "$JEOS_KEYTABLE" ]; then
     if findkeymaps \
         && d --default-item "$default" --menu  $"Select Keyboard Layout" 0 0 $dh_menu "${list[@]}"; then
         if [ -n "$result" ]; then
-            keytable="$result"
+            JEOS_KEYTABLE="$result"
         fi
     else
         d --msgbox $"Error setting keyboard" 0 0
     fi
-else
-    keytable="$JEOS_KEYTABLE"
 fi 
 
-if [ ! -z "$locale" -a ! -z "$keytable" ]; then
+if [ ! -z "$JEOS_LOCALE" -a ! -z "$JEOS_KEYTABLE" ]; then
     # Activate the selected keyboard layout
-    run langset.sh "$locale" "$keytable" || warn $"Setting the keyboard layout failed"
+    run langset.sh "$JEOS_LOCALE" "$JEOS_KEYTABLE" || warn $"Setting the keyboard layout failed"
 fi
 
 
-[ -n "${locale}" ] && language="${locale%%_*}" || language="en"
+[ -n "$JEOS_LOCALE" ] && language="${JEOS_LOCALE%%_*}" || language="en"
 force_english_license=0
-export LANG="$locale"
+export LANG="$JEOS_LOCALE"
 
 if [[ "$(ps h -o tty -p $$)" = tty[0-9]* ]]; then
     # Those languages can't be displayed in the console
@@ -247,12 +242,7 @@ if [[ "$(ps h -o tty -p $$)" = tty[0-9]* ]]; then
     start_kmscon["zh"]=1
     start_kmscon["ko"]=1
 
-    if [ -n "$locale" -a -n "${start_kmscon[${language}]+_}" ]; then
-	# We re-export the variables, as will be inspected when this
-	# script is re-executed in the secondary console
-        export JEOS_LOCALE="$locale"
-        export JEOS_KEYTABLE="$keytable"
-
+    if [ -n "$JEOS_LOCALE" -a -n "${start_kmscon[${language}]+_}" ]; then
         if kmscon_available; then
             ret_file="$(mktemp)"
             kmscon --silent --font-size 10 --palette vga --no-reset-env -l -- /bin/sh -c "$0; echo \$? > $ret_file; kill \$PPID"
@@ -280,8 +270,8 @@ fi
 
 if [ -e "$EULA_FILE" -a ! -e "${EULA_FILE%/*}/no-acceptance-needed" ]; then
     if [ "$force_english_license" = "0" ]; then
-        for i in "${EULA_FILE%.txt}.$locale.txt" \
-                "${EULA_FILE%.txt}.${locale%%.UTF-8}.txt" \
+        for i in "${EULA_FILE%.txt}.${JEOS_LOCALE}.txt" \
+                "${EULA_FILE%.txt}.${JEOS_LOCALE%%.UTF-8}.txt" \
                 "${EULA_FILE%.txt}.${language}.txt"; do
             if [ -e "$i" ]; then
             EULA_FILE="$i"
