More advanced version of running external scripts within firstboot

diff --git a/files/usr/lib/jeos-firstboot b/files/usr/lib/jeos-firstboot
--- a/files/usr/lib/jeos-firstboot
+++ b/files/usr/lib/jeos-firstboot
@@ -471,11 +471,28 @@ if [ "$config_wireless" = "true" ]; then
     run ifup $wlan_device || true
 fi
 
-# Execute external script(s) on firstboot
-if [ -d "/usr/lib/jeos-firstboot.d" ]; then
-    for script in /usr/lib/jeos-firstboot.d/??-*; do
-        if [ -x "${script}" ]; then
-            run "${script}"
+if [ -d "/usr/share/jeos-firstboot" ]; then
+    # Load all available modules
+    pushd "/usr/share/jeos-firstboot"
+    for module in *; do
+        source $module && modules+=("$module")
+    done
+    popd
+
+    # Run all systemd_firstboot hooks
+    for module in "${module[@]}"; do
+        # First run main function or bail out if not available
+        [ $(type -f "${module}_systemd_firstboot") = "function" ] || continue
+        "${module}_systemd_firstboot"
+
+        # Check if post function is available
+        if [ $(type -f "${module}_post") = "function" ]; then
+            "${module}_post"
+        fi
+
+        # Check if cleanup function is available
+        if [ $(type -f "${module}_cleanup") = "function" ]; then
+            "${module}_cleanup"
         fi
     done
 fi
